version: '3.9'

# Production-optimized Docker Compose configuration
services:
  frontend:
    container_name: weddingtravel-production
    build:
      context: .
      target: production
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - NODE_ENV=production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - TZ=UTC
    networks:
      - weddingtravel-network
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  weddingtravel-network:
    driver: bridge